// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageKnowledgeDao is the data access object for the table manage_knowledge.
// You can define custom methods on it to extend its functionality as needed.
type manageKnowledgeDao struct {
	*internal.ManageKnowledgeDao
}

var (
	// ManageKnowledge is a globally accessible object for table manage_knowledge operations.
	ManageKnowledge = manageKnowledgeDao{internal.NewManageKnowledgeDao()}
)

// Add your custom methods and functionality below.
