// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageDeviceDao is the data access object for the table manage_device.
// You can define custom methods on it to extend its functionality as needed.
type manageDeviceDao struct {
	*internal.ManageDeviceDao
}

var (
	// ManageDevice is a globally accessible object for table manage_device operations.
	ManageDevice = manageDeviceDao{internal.NewManageDeviceDao()}
)

// Add your custom methods and functionality below.
