// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageSensorDao is the data access object for the table manage_sensor.
// You can define custom methods on it to extend its functionality as needed.
type manageSensorDao struct {
	*internal.ManageSensorDao
}

var (
	// ManageSensor is a globally accessible object for table manage_sensor operations.
	ManageSensor = manageSensorDao{internal.NewManageSensorDao()}
)

// Add your custom methods and functionality below.
