// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageAlarmLabelDao is the data access object for the table manage_alarm_label.
// You can define custom methods on it to extend its functionality as needed.
type manageAlarmLabelDao struct {
	*internal.ManageAlarmLabelDao
}

var (
	// ManageAlarmLabel is a globally accessible object for table manage_alarm_label operations.
	ManageAlarmLabel = manageAlarmLabelDao{internal.NewManageAlarmLabelDao()}
)

// Add your custom methods and functionality below.
