// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageSensorTypeDao is the data access object for the table manage_sensor_type.
// You can define custom methods on it to extend its functionality as needed.
type manageSensorTypeDao struct {
	*internal.ManageSensorTypeDao
}

var (
	// ManageSensorType is a globally accessible object for table manage_sensor_type operations.
	ManageSensorType = manageSensorTypeDao{internal.NewManageSensorTypeDao()}
)

// Add your custom methods and functionality below.
