// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageServerDao is the data access object for the table manage_server.
// You can define custom methods on it to extend its functionality as needed.
type manageServerDao struct {
	*internal.ManageServerDao
}

var (
	// ManageServer is a globally accessible object for table manage_server operations.
	ManageServer = manageServerDao{internal.NewManageServerDao()}
)

// Add your custom methods and functionality below.
