// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageAlarmDao is the data access object for the table manage_alarm.
// You can define custom methods on it to extend its functionality as needed.
type manageAlarmDao struct {
	*internal.ManageAlarmDao
}

var (
	// ManageAlarm is a globally accessible object for table manage_alarm operations.
	ManageAlarm = manageAlarmDao{internal.NewManageAlarmDao()}
)

// Add your custom methods and functionality below.
