// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageDeviceControlDao is the data access object for the table manage_device_control.
// You can define custom methods on it to extend its functionality as needed.
type manageDeviceControlDao struct {
	*internal.ManageDeviceControlDao
}

var (
	// ManageDeviceControl is a globally accessible object for table manage_device_control operations.
	ManageDeviceControl = manageDeviceControlDao{internal.NewManageDeviceControlDao()}
)

// Add your custom methods and functionality below.
