// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageAreaDao is the data access object for the table manage_area.
// You can define custom methods on it to extend its functionality as needed.
type manageAreaDao struct {
	*internal.ManageAreaDao
}

var (
	// ManageArea is a globally accessible object for table manage_area operations.
	ManageArea = manageAreaDao{internal.NewManageAreaDao()}
)

// Add your custom methods and functionality below.
