// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageThresholdDao is the data access object for the table manage_threshold.
// You can define custom methods on it to extend its functionality as needed.
type manageThresholdDao struct {
	*internal.ManageThresholdDao
}

var (
	// ManageThreshold is a globally accessible object for table manage_threshold operations.
	ManageThreshold = manageThresholdDao{internal.NewManageThresholdDao()}
)

// Add your custom methods and functionality below.
