// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageSensorControlDao is the data access object for the table manage_sensor_control.
// You can define custom methods on it to extend its functionality as needed.
type manageSensorControlDao struct {
	*internal.ManageSensorControlDao
}

var (
	// ManageSensorControl is a globally accessible object for table manage_sensor_control operations.
	ManageSensorControl = manageSensorControlDao{internal.NewManageSensorControlDao()}
)

// Add your custom methods and functionality below.
