// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageOpcDao is the data access object for the table manage_opc.
// You can define custom methods on it to extend its functionality as needed.
type manageOpcDao struct {
	*internal.ManageOpcDao
}

var (
	// ManageOpc is a globally accessible object for table manage_opc operations.
	ManageOpc = manageOpcDao{internal.NewManageOpcDao()}
)

// Add your custom methods and functionality below.
