// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"devinggo/manage/dao/internal"
)

// manageEventDao is the data access object for the table manage_event.
// You can define custom methods on it to extend its functionality as needed.
type manageEventDao struct {
	*internal.ManageEventDao
}

var (
	// ManageEvent is a globally accessible object for table manage_event operations.
	ManageEvent = manageEventDao{internal.NewManageEventDao()}
)

// Add your custom methods and functionality below.
